# ------------------------------------------------------------------------
# Copyright (c) 2022 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: HDCAnet_Encoder
model_type: BlindSSRModel
scale: 4
num_gpu: 1
manual_seed: 10

datasets:
  train:
    name: Real-Flickr1024train
    type: BlindSSRModel
    dataroot_gt: /LinPeiMing/Dataset/Real-Flickr1024/train/hr
    dataroot_lq: /LinPeiMing/Dataset/Real-Flickr1024/train/lr_x4
    io_backend:
      type: disk

    gt_size_h: 120
    gt_size_w: 360
    use_hflip: true
    use_vflip: true
    use_rot: false
    flip_RGB: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

# network structures
network_g:
  type: BlindSSR_E

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
#  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-3
    weight_decay: !!float 0
    betas: [0.9, 0.999]

  scheduler:
    type: MultiStepLR
    milestones: [18000]
    gamma: !!float 1e-1


  total_iter: 30000
  warmup_iter: -1 # no warm up
  mixup: false

  # losses
  contrastive_opt:
    type: CrossEntropyLoss
    loss_weight: 1.0
    reduction: mean

# logging settings
logger:
  print_freq: 500
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
